; PlatformIO Project Configuration File
; Projeto: Monitor de Datacenter
; Placa: BlackBoard Wisdom (RoboCore) — ESP32

[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 9600

lib_deps =
    mobizt/Firebase ESP32 Client@^4.4.17
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    sparkfun/SparkFun APDS9960 RGB and Gesture Sensor@^1.4.3
    sparkfun/SparkFun HTU21D Humidity and Temperature Sensor Breakout@^1.1.3

; Opcional: aumenta o tamanho da stack para tarefas pesadas (Firebase + SSL)
build_flags =
    -DCORE_DEBUG_LEVEL=0